# master makefile

spectral:spectral.f90
	gfortran -c -O3  --openmp spectral.f90
	gfortran -o  spectral --openmp spectral.o

spectral_leg:spectral_leg.f90
	gfortran -c -O3  --openmp spectral_leg.f90
	gfortran -o  spectral_leg --openmp spectral_leg.o

disk:disk.f90
	gfortran -c -O3  --openmp disk.f90
	gfortran -o  disk --openmp disk.o

disk_dbl:disk_dbl.f90
	gfortran -c -O3  --openmp disk_dbl.f90
	gfortran -o  disk_dbl --openmp disk_dbl.o


manydisks:manydisks.f90
	gfortran -c -O3  --openmp manydisks.f90
	gfortran -o  manydisks --openmp manydisks.o

ring:ring.f90
	gfortran -c -O3  --openmp ring.f90
	gfortran -o  ring --openmp ring.o

ring_dbl:ring_dbl.f90
	gfortran -c -O3  --openmp ring_dbl.f90
	gfortran -o  ring_dbl --openmp ring_dbl.o

ellipse:ellipse.f90
	gfortran -c -O3  --openmp ellipse.f90
	gfortran -o  ellipse --openmp ellipse.o

ellipse_dbl:ellipse_dbl.f90
	gfortran -c -O3  --openmp ellipse_dbl.f90
	gfortran -o  ellipse_dbl --openmp ellipse_dbl.o

square_dbl:square_dbl.f90
	gfortran -c -O3  --openmp square_dbl.f90
	gfortran -o  square_dbl --openmp square_dbl.o

square_dbl_leg:square_dbl_leg.f90
	gfortran -c -O3  --openmp square_dbl_leg.f90
	gfortran -o  square_dbl_leg --openmp square_dbl_leg.o

smoothstar:smoothstar.f90
	gfortran -c -O3  --openmp smoothstar.f90
	gfortran -o  smoothstar --openmp smoothstar.o
smoothstar_dbl:smoothstar_dbl.f90
	gfortran -c -O3  --openmp smoothstar_dbl.f90
	gfortran -o  smoothstar_dbl --openmp smoothstar_dbl.o
